### PR TITLE
feat: basic client implementation

### PR DESCRIPTION
**Pull request by lukasberbuer**
Prior discussions in #20 and #23.

### CODE REVIEW

**Comment by lukasberbuer** [comment]
@duca, I just focused on the discovery so far. There are some decision I'm unsure about:
1. `Client::findServers` and `Client::getEndpoints` could be static methods. Disadvantage: The client config can not be modified, for example to adjust timeouts. Or we add an argument to pass an optional `UA_ClientConfig`.
2. `Client` could be constructed with the `serverUrl` directly so we don't have to pass it to the `connect` method etc. This makes primarily sense if the methods of 1 are static. The Python library `asyncua` chooses this approach: https://opcua-asyncio.readthedocs.io/en/latest/api/asyncua.client.html#asyncua.client.client.Client

**Comment by duca** [comment]
> @duca, I just focused on the discovery so far. There are some decision I'm unsure about:
> 
> 1. `Client::findServers` and `Client::getEndpoints` could be static methods. Disadvantage: The client config can not be modified, for example to adjust timeouts. Or we add an argument to pass an optional `UA_ClientConfig`.
> 2. `Client` could be constructed with the `serverUrl` directly so we don't have to pass it to the `connect` method etc. This makes primarily sense if the methods of 1 are static. The Python library `asyncua` chooses this approach: https://opcua-asyncio.readthedocs.io/en/latest/api/asyncua.client.html#asyncua.client.client.Client

Regarding 1., I think it is fine to pass a UA_ClientConfig (or a wrapper for it) as argument to the static methods

Regarding 2: agreed, matches fine with 1 approach and allows for simple RAII-esque approach

**Comment by lukasberbuer** [comment]
@duca, I had some time and implemented the `NodeManagement` and `Attribute` service set for the client. The free functions made those additions really easy. I'm quite happy with the outcome.

One of the most important client features is missing: browsing! But this is also missing for the server so far.
Maybe we can merge this branch first and work on the browsing feature for both.

Do you have any further suggestions, API proposals etc.?

**Comment by lukasberbuer** [comment]
> > @duca, I just focused on the discovery so far. There are some decision I'm unsure about:
> > 
> > 1. `Client::findServers` and `Client::getEndpoints` could be static methods. Disadvantage: The client config can not be modified, for example to adjust timeouts. Or we add an argument to pass an optional `UA_ClientConfig`.
> > 2. `Client` could be constructed with the `serverUrl` directly so we don't have to pass it to the `connect` method etc. This makes primarily sense if the methods of 1 are static. The Python library `asyncua` chooses this approach: https://opcua-asyncio.readthedocs.io/en/latest/api/asyncua.client.html#asyncua.client.client.Client
> 
> Regarding 1., I think it is fine to pass a UA_ClientConfig (or a wrapper for it) as argument to the static methods
> 
> Regarding 2: agreed, matches fine with 1 approach and allows for simple RAII-esque approach

I fear that we will introduce too much overhead with the static methods. I just saw that the types `UA_ClientConfig` and `UA_ServerConfig`  are huge (> 500 bytes). The configs have to be created with every `findServer` or `getEndpoints` call if those are static methods...

**Comment by duca** [comment]
> > > @duca, I just focused on the discovery so far. There are some decision I'm unsure about:
> > > 
> > > 1. `Client::findServers` and `Client::getEndpoints` could be static methods. Disadvantage: The client config can not be modified, for example to adjust timeouts. Or we add an argument to pass an optional `UA_ClientConfig`.
> > > 2. `Client` could be constructed with the `serverUrl` directly so we don't have to pass it to the `connect` method etc. This makes primarily sense if the methods of 1 are static. The Python library `asyncua` chooses this approach: https://opcua-asyncio.readthedocs.io/en/latest/api/asyncua.client.html#asyncua.client.client.Client
> > 
> > 
> > Regarding 1., I think it is fine to pass a UA_ClientConfig (or a wrapper for it) as argument to the static methods
> > Regarding 2: agreed, matches fine with 1 approach and allows for simple RAII-esque approach
> 
> I fear that we will introduce too much overhead with the static methods. I just saw that the types `UA_ClientConfig` and `UA_ServerConfig` are huge (> 500 bytes). The configs have to be created with every `findServer` or `getEndpoints` call if those are static methods...

What if we had Client and Server as a global or as a singleton? We would need to set them up once and forget, right?

**Comment by duca** [comment]
> @duca, I had some time and implemented the `NodeManagement` and `Attribute` service set for the client. The free functions made those additions really easy. I'm quite happy with the outcome.
> 
> One of the most important client features is missing: browsing! But this is also missing for the server so far. Maybe we can merge this branch first and work on the browsing feature for both.
> 
> Do you have any further suggestions, API proposals etc.?

I do have a working browse implementation on the client side, the API is extremely simple:

https://github.com/duca/open62541pp/blob/master/include/open62541pp/Browser.h
https://github.com/duca/open62541pp/blob/master/src/Browser.cpp

**Comment by duca** [comment]
I added a constructor in my NodeClient class that accepted a RefereceDescription besides the client and it is usable right now.

**Pull request merged**
