### PR TITLE
client pieces

### PR DESCRIPTION
**Pull request by duca**
This has the prototype NodeClient and Client to be used as starting point of the Client implementation. Currently Client is severely lacking if compared with the Server class, however NodeClient is very similar to Node in functionality. Some features were commented out just because I didn't have the time to finalize and test them.

I am new to PRs on Github, so pardon me for opening one to master instead of a separate client-specific branch

### CODE REVIEW

**Comment by duca** [comment]
> Thanks @duca for your work!
> 
> I would like to split up this massive pull request into smaller ones, e.g.:
> 
> 1. Minimal `Client` class with basic functionality to connect to servers
> 2. Templated `Node<ServerOrClient>` class
> 3. Free functions in `services` namespace for `Client` class. The `Node` class just calls those free functions with the templated `ClientOrServer` type. If there is no function overload for `Client`, you'll get a compile error. So we can start slowly with a minimal set of overloaded functions and add more over the time.
> 4. `ReferenceDescription` wrapper and browsing for both `Client` and `Server` with free functions and `Node` interface.
>    I hesitated to implement wrapper classes for composed types like `ReferenceDescription`, because you usually have to do copies of wrapper objects in the getter and setter methods. I want to address this topic as descibed in [Efficient wrapper of composed types #30](https://github.com/open62541pp/open62541pp/issues/30).
> 5. `open62541ppConfig.cmake` and install targets for CMake
> 
> I will work on the composed wrappers (4) and the templated `Node` class (2). I can also provide a minimal `Client` class (1) if you like.
> 
> What would you like to work on?

@lukasberbuer , i would like to pick 1, 3, and 5.

**Comment by lukasberbuer** [comment]
@duca, I already started with a `Client` skeleton yesterday. Let me push this to a new branch first and then extend this?

Btw, I forgot all the async stuff you already did. I would propose to implement the sync interface first and add the async interface later.

**Comment by duca** [comment]
> @duca, I already started with a `Client` skeleton yesterday. Let me push this to a new branch first and then extend this?
> 
> Btw, I forgot all the async stuff you already did. I would propose to implement the sync interface first and add the async interface later.

Thankfully, I didn't do any async work yet :)
I had a pretty busy week, so I didn't have the time yet to generate my skeleton client.

**Comment by lukasberbuer** [comment]
Just a small update:

1, 2 and 3 are finished within pull request #33.
Now we can focus on the browsing. But I would like to do the merge first. Anything you want to add/change before?

**Comment by duca** [comment]
> Just a small update:
> 
> 1, 2 and 3 are finished within pull request #33. Now we can focus on the browsing. But I would like to do the merge first. Anything you want to add/change before?

I finally got the time to split this PR and you will see item 5 in PR #38

**Comment by duca** [comment]
closing this one because it is now obsolete. Item #4 is being already discussed in the scope of issue [3](https://github.com/open62541pp/open62541pp/issues/30)

**Comment by duca** [comment]
closing this one because it is now obsolete. Item #4 is being already discussed in the scope of issue [3](https://github.com/open62541pp/open62541pp/issues/30)

**Pull request closed without merging**
